### PR TITLE
Use MPI wrappers for TIOGA on Darwin.

### PR DESCRIPTION
**Pull request by jrood-nrel**
Also remove ninja for everything but Trilinos.

### CODE REVIEW

**Comment by psakievich** [comment]
Should we just get rid of ninja for Trilinos too?  Is it worth keeping around if we have to fight with it?  It seems like an all or nothing kind of thing to me.

**Comment by jrood-nrel** [comment]
It actually seems to work for trilinos and it gives us the most benefit, where it has constantly burned me in other packages. I don't see it as all or nothing.

**Comment by psakievich** [comment]
Okay I'll follow your lead.

**Review by psakievich — COMMENTED** [review]
LGTM

**Pull request merged**
