### PR TITLE
update rocm versions in crusher/spock configs

### PR DESCRIPTION
**Pull request by tasmith4**
Breaking up #352 into more digestable chunks that we can (hopefully) get merged into main faster.

@PaulMullowney @jrood-nrel @psakievich @ddement @djglaze

### CODE REVIEW

**Comment by PaulMullowney** [comment]
Are these PRs based off the most up-to-date version of my branch? I rebased yesterday and pushed.

**Comment by tasmith4** [comment]
> Are these PRs based off the most up-to-date version of my branch? I rebased yesterday and pushed.

Yes they are.  I'm still struggling a little with the Trilinos one, your version of that is not building for me.  But I wanted to get the other stuff in without it being delayed by the Trilinos package.

**Comment by PaulMullowney** [comment]
Trilinos needs to be patched. The patch to nemesis tests is gonna go into trilinos develop soon (https://github.com/trilinos/Trilinos/pull/11210). I don't know what's wrong with exo_format.
````
diff --git a/packages/seacas/applications/exo_format/CMakeLists.txt b/packages/seacas/applications/exo_format/CMakeLists.txt
index dd8de28be3d..4fcf6c2b1c3 100644
--- a/packages/seacas/applications/exo_format/CMakeLists.txt
+++ b/packages/seacas/applications/exo_format/CMakeLists.txt
@@ -12,14 +12,14 @@ APPEND_GLOB(SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/*.c)
 #this error only seems to manifest on pgi 11.1, however, the version of the compiler
 #is not given for pgi compilers unfortunately so we can't be more specific
 IF(NOT __LINUX_COMPILER_PGI)
-  TRIBITS_ADD_EXECUTABLE(
-    exo_format
-    NOEXEPREFIX
-    NOEXESUFFIX
-    SOURCES ${SOURCES}
-    COMM serial mpi
-    INSTALLABLE
-    )
+  #TRIBITS_ADD_EXECUTABLE(
+  #  exo_format
+  #  NOEXEPREFIX
+  #  NOEXESUFFIX
+  #  SOURCES ${SOURCES}
+  #  COMM serial mpi
+  #  INSTALLABLE
+  #  )
 ENDIF()

 TRIBITS_SUBPACKAGE_POSTPROCESS()
diff --git a/packages/seacas/libraries/nemesis/CMakeLists.txt b/packages/seacas/libraries/nemesis/CMakeLists.txt
index a2546ee5e82..00eacc52b96 100644
--- a/packages/seacas/libraries/nemesis/CMakeLists.txt
+++ b/packages/seacas/libraries/nemesis/CMakeLists.txt
@@ -34,11 +34,11 @@ IF (${PACKAGE_NAME}_ENABLE_TESTS)
     NAME ne_ctest_wrap
     NUM_MPI_PROCS 1
     )
-ENDIF()

 TRIBITS_ADD_EXECUTABLE(
   ne_ctest_wrap
   SOURCES ne_ctest_wrap.c
   )
+ENDIF()
````

**Review by PaulMullowney — COMMENTED** [review]
I can't approve for some reason because I don't have explicit access.
Anyway, I approve.

**Review by psakievich — APPROVED** [review]

**Pull request merged**
