### PR TITLE
Update Spack submodule

### PR DESCRIPTION
**Pull request by jrood-nrel**
We need this commit from Spack https://github.com/spack/spack/pull/32182

### CODE REVIEW

**Review by psakievich — APPROVED** [review]
Looks like we are hitting new style issues due to spack using black as a new formatter.  If you run `spack style -f` it should fix everything.

**Comment by jrood-nrel** [comment]
Hmm
```
==> Running isort checks
  isort checks were clean
==> Running mypy checks
Success: no issues found in 556 source files
  mypy checks were clean
==> Running black checks
  black checks were clean
==> Running flake8 checks
  flake8 checks were clean
==> spack style checks were clean
```

**Comment by jrood-nrel** [comment]
Ah I figured it out.

**Comment by jrood-nrel** [comment]
I'm not sure I know how to fix the warnings though.

**Pull request merged**
