### PR TITLE
Tiny Profile Variants

### PR DESCRIPTION
**Pull request by PaulMullowney**
Adding tiny profile variants

### CODE REVIEW

**Comment by psakievich** [comment]
This was already added in mainline spack: https://github.com/spack/spack/pull/34993. So we shouldn't need the amr-wind one.

**Review by psakievich — CHANGES_REQUESTED** [review]
Let's use the Tiny Profile variant added in https://github.com/spack/spack/pull/34993

**Comment by PaulMullowney** [comment]
> Let's use the Tiny Profile variant added in [spack/spack#34993](https://github.com/spack/spack/pull/34993)

Ok, but should it propagate from exawind?

**Comment by psakievich** [comment]
I'm fine with having it as an exawind variant. No objections from me there.

**Review by psakievich — APPROVED** [review]

**Pull request merged**
