### PR TITLE
Add hdf5 option to amr-wind

### PR DESCRIPTION
**Pull request by jrood-nrel**
This has a few major changes like updating Spack and changing the HDF5 version, but I think we should make them.

### CODE REVIEW

**Review by psakievich — COMMENTED** [review]
I think these all look reasonable to me. Updating HDF5 will cause a lot of rebuilds though so we should probably make an announcement about it on the spack-manager slack channel.

**Comment by jrood-nrel** [comment]
I'm still working through this because Spack builds HDF5 through CMake now which causes all kinds of issues. CMake's FindHDF5 is much better when HDF5 is built with autotools.

**Comment by psakievich** [comment]
Closes #281

**Comment by jrood-nrel** [comment]
Also, I want to note I didn't inherit here `h5z-zfp` because its build system changed to cmake on the master branch which is what we want here. I have https://github.com/spack/spack/pull/29952 open, but in my opinion the `package.py` here is what should be in Spack and the versions before cmake for `h5z-zfp` should be ignored.

**Comment by psakievich** [comment]
Yeah this looks good. I feel like your package changes wont get merged until @alalazo finishes his work supporting multiple build systems.

**Pull request merged**
