### PR TITLE
Add numeric versions to Trilinos and remove stable version

### PR DESCRIPTION
**Pull request by psakievich**
If a user already has `trilinos@stable` in it the `--reuse` will pick it up, but using `--fresh` will pick up the new "stable" version of trilinos

### CODE REVIEW

**Comment by psakievich** [comment]
supersedes portions of #382

**Review by tasmith4 — APPROVED** [review]
I think this is reasonable.  But I don't have strong opinions on how the stable versions of Trilinos are named so would like to hear from @jrood-nrel also.

**Comment by jrood-nrel** [comment]
I'm fine with the naming updates. I just realized the proposed Trilinos commit doesn't build with the Intel compiler so I think we should wait on upgrading Trilinos until that is fixed.

**Comment by psakievich** [comment]
closes #382

**Comment by psakievich** [comment]
@jrood-nrel I can't conditionally set the trilinos config on eagle like I thought.  Spack still needs to implement this functionality.  However, maintaining the versions and cxx14 option gives an intel path forward for now.  I've updated the rhodes testing to show how to do this.

**Review by jrood-nrel — APPROVED** [review]
Is the Spack submodule update intentional?

**Comment by psakievich** [comment]
@jrood-nrel yes it is to allow for https://github.com/spack/spack/commit/6990cf76a0d167db844373d8b643d42cd3282049

Which enables us to use this trilinos versioning scheme.

**Pull request merged**
