### PR TITLE
Update Spack to capture UVM variant for Trilinos

### LINKED ISSUE #185: Need a spec to turn off Cuda UVM
I would like to be able to turn off UVM for Cuda builds with something like:

`exawind+hypre ^nalu-wind ^trilinos~cuda_uvm`

### PR DESCRIPTION
**Pull request by psakievich**
Trilinos package has turned off UVM in the latest spack.

Closes #185

### CODE REVIEW

**Review by tasmith4 — CHANGES_REQUESTED** [review]
As discussed in #185, this is almost certain to break Nalu-Wind Cuda builds/runs.

**Comment by psakievich** [comment]
Tracking https://github.com/spack/spack/pull/28949. Will update spack when this gets merged

**Review by tasmith4 — CHANGES_REQUESTED** [review]
I don't see where this pulls in the latest spack that includes the trilinos package update, did I miss something?

**Review by tasmith4 — APPROVED** [review]
never mind I found it

**Pull request merged**
